version: '3.8'

services:
  db:
    image: postgres:13
    container_name: meetup-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetup
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meetup"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/meetup?schema=public
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:dev"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
